language: node_js
node_js:
  - '6'
  - '8'
  - '10'
before_install:
  - npm i -g npm@latest
install:
  - npm ci
sudo: false
script: "npm run coverage"
after_success:
  - cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
