environment:
  matrix:
  - nodejs_version: "4"
  - nodejs_version: "6"
  - nodejs_version: "8"
  - nodejs_version: "10"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm ci

test_script:
  - node --version
  - npm --version
  - npm test

version: 1.0.{build}
skip_tags: true
build: off
