environment:
  matrix:
  - nodejs_version: "4"
  - nodejs_version: "6"
  - nodejs_version: "8"
  - nodejs_version: "10"

build_script:
  - npm i -g npm@latest

install:
  - ps: Install-Product node $env:nodejs_version
  - npm ci

test_script:
  - node --version
  - npm --version
  - npm test

version: 1.0.{build}
skip_tags: true
build: off
